language: java
jdk:
  - oraclejdk7
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install -y pandoc
before_script:
  - wget "http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz"  -O "/tmp/kindlegen.tar.gz"
  - tar -xvf /tmp/kindlegen.tar.gz
  - export PATH=$PATH:$PWD/kindlegen_linux_2.6_i386_v2_9/
  - cd latex2mobi-converter
